### ISSUE TITLE
Update to 1.21.4 Please

### ISSUE THREAD

**Issue by sternschnaube** [Snownee/Companion#29]
### Mod loader

Fabric

### Minecraft version

1.20.2

### Mod version

Latest (5.1.0)

### Modloader version

0.15.0

### If bug:

- [ ] Can you reproduce this issue with relevant mods only?

### Issue description

Tested just on the server-side.

**Comment by venaminecraft** [comment]
Seems to work on 1.20.6, needs more testing from my side.
Running just server-side.

**Comment by venaminecraft** [comment]
Encountered an unexpected exception
net.minecraft.class_148: Exception ticking world
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:1002) ~[server-intermediary.jar:?]
	at net.minecraft.class_3176.method_3813(class_3176.java:294) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:889) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:691) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:275) ~[server-intermediary.jar:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Caused by: java.lang.NoSuchMethodError: 'net.minecraft.class_7 net.minecraft.class_14.method_23476(net.minecraft.class_1922, net.minecraft.class_2338$class_2339)'
	at snownee.companion.Hooks.canTeleportTo(Hooks.java:150) ~[Companion-1.20-fabric-5.1.0.jar:?]
	at snownee.companion.Hooks.teleportWithRandomOffset(Hooks.java:138) ~[Companion-1.20-fabric-5.1.0.jar:?]
	at snownee.companion.Hooks.handleChunkPreUnload(Hooks.java:183) ~[Companion-1.20-fabric-5.1.0.jar:?]
	at net.minecraft.class_5579.md60be3f$companion$lambda$companion_tick$0$0(class_5579.java:1568) ~[server-intermediary.jar:?]
	at it.unimi.dsi.fastutil.longs.LongOpenHashSet.forEach(LongOpenHashSet.java:762) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.longs.LongIterable.forEach(LongIterable.java:146) ~[fastutil-8.5.12.jar:?]
	at it.unimi.dsi.fastutil.longs.AbstractLongCollection.forEach(AbstractLongCollection.java:153) ~[fastutil-8.5.12.jar:?]
	at net.minecraft.class_5579.handler$dgo004$companion$tick(class_5579.java:1563) ~[server-intermediary.jar:?]
	at net.minecraft.class_5579.method_31809(class_5579.java:358) ~[server-intermediary.jar:?]
	at net.minecraft.class_3218.method_18765(class_3218.java:416) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$method_18765$390(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.wrapOperation$bdd000$carpet-ams-addition$tickWorlds(MinecraftServer.java:5575) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.mixinextras$bridge$wrapOperation$bdd000$carpet-ams-addition$tickWorlds$391(MinecraftServer.java) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.wrapOperation$ddi000$carpet-tis-addition$yeetUpdateSuppressionCrash_implOnTickWorlds(MinecraftServer.java:9077) ~[server-intermediary.jar:?]
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:998) ~[server-intermediary.jar:?]
	... 5 more

**Comment by XandarNull** [comment]
I would love it if the devs updated the mod to work with Minecraft 1.21

**Comment by Riyuukii** [comment]
hi! any update on this? companion is one of my most favorite mods that I cannot live without; I wish they considered updating this mod to 1.21!

**Comment by Fyoncle** [comment]
@Snownee Can we get news?

**Comment by Keaton42** [comment]
I really want this on 1.21 as well!! It adds so much to the game and makes me enjoy pets!!

**Comment by venaminecraft** [comment]
Any update @Snownee? 😄
And did you managed to defeat the Ender Dragon? 😆

**Comment by Snownee** [comment]
1.21.1 port will be released soooon. And I will no longer port mods to versions like 1.21.4 in the future

**Comment by venaminecraft** [comment]
Good to know, thanks. I can understand the hassle Mojang is putting on mod developers with the new update rhythm...

**Comment by Keaton42** [comment]
Thanks!! This is very much appreciated, I’m always excited to see my favorite mods on my waitlist get updated to my favorite version! ❤️💯
